 version: 2.1

 executors:
  netcore:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

 jobs:
   build:
     executor: netcore 
    
     steps:
       - checkout
       - run:
           name: dotnet build
           command: |
             dotnet build ./DummyConsole/DummyConsole.sln
       - run:
            name: echo from App build
            command: |
              echo dotnet ./DummyConsole/bin/Debug/netcoreapp3.1/DummyConsole.dll